name: Patch Release

on:
  workflow_dispatch:
    inputs:
      release:
        required: true

permissions:
  contents: write

jobs:
  semgrep:
    permissions:
      contents: read
    name: Semgrep Patches
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      # Checkout project source
      - uses: actions/checkout@v4
        with:
          repository: hashicorp/raft
          ref: "${{ github.event.inputs.release }}"
          path: ./upstream
      - uses: actions/checkout@v4
        with:
          path: ./patcher
      - run: semgrep scan -c ../patcher/semgrep_rules --autofix
        working-directory: ./upstream
      - run: semgrep scan -c ../patcher/semgrep_rules --autofix
        working-directory: ./upstream
      - name: Upload patched code
        uses: actions/upload-artifact@v3
        with:
          name: "upstream-patched-${{ github.event.inputs.release }}"
          path: |
            ./upstream/
            !./upstream/.git
  gomods:
    permissions:
      contents: read
    needs: semgrep
    name: Go Mod changes
    runs-on: ubuntu-latest
    steps:
    - name: Download patched upstream
      uses: actions/download-artifact@v3
      with:
        name: "upstream-patched-${{ github.event.inputs.release }}"
        path: ./patched
    - uses: actions/checkout@v4
      with:
        path: ./patcher
    - name: Setup Go environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        check-latest: true
        cache-dependency-path: ./patched/go.sum
    - name: Run in-repo script to finish patching
      run: ../patcher/patch.sh
      working-directory: ./patched
    - name: Upload patched code
      uses: actions/upload-artifact@v3
      with:
        name: "upstream-patched-final-${{ github.event.inputs.release }}"
        path: ./patched/
